2020-04-09 16:36:30,359 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:43]
2020-04-09 16:49:33,576 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:43]
2020-04-09 17:22:22,969 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:43]
2020-04-09 17:25:42,676 ERROR: Exception on /reset_password_request [POST] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\super\Knowland\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\super\Knowland\app\email.py", line 20, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2020-04-09 17:27:29,475 ERROR: Exception on /reset_password_request [POST] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\super\Knowland\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\super\Knowland\app\email.py", line 20, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2020-04-11 21:03:28,910 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:43]
2020-04-11 21:05:11,598 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:43]
2020-04-11 21:05:32,355 ERROR: Exception on /user/trollface959 [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\super\Knowland\app\routes.py", line 87, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\super\Knowland\app\templates\user.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 32, in top-level template code
    {% block content %}
  File "C:\Users\super\Knowland\app\templates\user.html", line 15, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\super\knowland\knowland_start\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'explore' instead?
